# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-10-18 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_filename', models.CharField(max_length=100)),
                ('breed', models.CharField(default='unknown', max_length=100)),
                ('age', models.IntegerField(help_text='Months in number')),
                ('gender', models.CharField(help_text='[M]ale [F]emale [U]nknown', max_length=1)),
                ('size', models.CharField(help_text='[S]mall [M]edium [L]arge [XL]arge [U]nknown', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='u', help_text='[L]iked [D]isliked', max_length=1)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pugorugh.Dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('b', 'baby'), ('y', 'young'), ('a', 'adult'), ('s', 'senior')], default='b,y,a,s', help_text='[B]aby [Y]oung [A]dult [S]enior', max_length=7)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m,f', help_text='"[M]ale [F]emale', max_length=3)),
                ('size', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large')], default='s,m,l,xl', help_text='[S]mall [M]edium [L]arge [XL]arge', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
