# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-10-21 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', help_text='[B]aby [Y]oung [A]dult [S]enior', max_length=7),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(default='m,f', help_text='"[M]ale [F]emale', max_length=3),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='s,m,l,xl', help_text='[S]mall [M]edium [L]arge [XL]arge', max_length=8),
        ),
    ]
